language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev swig
# command to install dependencies
install: pip install -r REQUIREMENTS --use-mirrors
# command to run tests
script: make build
after_success:
  - coveralls --base_dir=provy
